name: PyProgressTracker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Upload graphics.py and sys as artifacts
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: python-files
        path: |
          path/to/graphics.py
          path/to/sys.py

    - name: Lint with flake8
      run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Test with pytest
      run: pytest

    # Download graphics.py and sys from artifacts
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: python-files
        path: .
