# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: PyProgress Tracker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose a different operating system if needed

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have any external dependencies

    - name: Run Python script
      run: PyProgressTracker.py  # Replace with your script name
